# WIFI-gratis: hotspot internet biasa (share internet dari wlan0 "ruang tamu")
# via wlan2, OPEN/tanpa password sesuai permintaan user.
interface=wlan2
driver=nl80211
ssid=WIFI-gratis
country_code=ID
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
