per_listener_settings true

# ---- Persistence ----
persistence true
persistence_location /mosquitto/data/
autosave_interval 300

# ---- Logging ----
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
log_timestamp true

# ---- Listener: plain MQTT (internal network only, tidak di-expose ke WAN) ----
listener 1883
protocol mqtt
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

# ---- Listener: MQTT over TLS ----
listener 8883
protocol mqtt
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf
cafile   /mosquitto/certs/ca.pem
certfile /mosquitto/certs/fullchain.pem
keyfile  /mosquitto/certs/privkey.pem
tls_version tlsv1.3
require_certificate false

# ---- Listener: MQTT over WebSocket (di belakang nginx) ----
listener 9001
protocol websockets
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

# ---- Hardening ----
max_connections -1
max_keepalive 120
message_size_limit 268435
