#!/usr/bin/env python3
"""
session-to-cookies-txt.py -- konversi file sesi browser (storageState JSON
dari sessionSave/sessionLoad, akses-vps/backup/browser-profile-backup.sh)
ke format Netscape cookies.txt (kompatibel extension "Get cookies.txt
LOCALLY" + tool cookie-jar lain spt yt-dlp/curl --cookie).

Format sumber (envelope BrowserService.js#sessionSave, lihat
SessionPersistence.js di repo `browser`):
  {"version":1,"savedAt":"...","profile":"...","cookies":[
    {"name":..,"value":..,"domain":..,"path":..,"expires":<unix|-1>,
     "httpOnly":..,"secure":..,"sameSite":..}, ...
  ],"origins":[...]}

Pemakaian:
  python3 session-to-cookies-txt.py <session.json> [-o out.txt]
  python3 session-to-cookies-txt.py --stdin < session.json > out.txt
"""
import argparse
import json
import sys


def to_netscape(session):
    cookies = session.get("cookies", [])
    lines = ["# Netscape HTTP Cookie File", "# Generated by session-to-cookies-txt.py -- jangan edit manual", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # Playwright/CDP: domain tanpa titik depan = host-only cookie (flag FALSE),
        # domain dgn titik depan = berlaku ke semua subdomain (flag TRUE).
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires", -1)
        # Playwright pakai -1 utk session cookie (tak ada expiry) -> Netscape
        # konvensi umum: 0. exists tapi float -> bulatkan ke int detik.
        exp_int = 0 if expires is None or expires < 0 else int(expires)
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{exp_int}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("session_file", nargs="?", help="path file session .json (kosongkan kalau pakai --stdin)")
    ap.add_argument("--stdin", action="store_true", help="baca JSON dari stdin, bukan file")
    ap.add_argument("-o", "--out", help="tulis ke file ini (default: stdout)")
    args = ap.parse_args()

    if args.stdin:
        raw = sys.stdin.read()
    elif args.session_file:
        with open(args.session_file, "r", encoding="utf-8") as f:
            raw = f.read()
    else:
        ap.error("beri path file session ATAU --stdin")

    session = json.loads(raw)
    txt = to_netscape(session)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(txt)
        print(f"OK: {len(session.get('cookies', []))} cookie -> {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(txt)


if __name__ == "__main__":
    main()
