# DHCP hanya untuk klien AP (wlan2). Terisolasi dari uplink wlan0.
interface=wlan2
bind-interfaces
except-interface=wlan0
listen-address=10.20.30.1
dhcp-range=10.20.30.50,10.20.30.150,255.255.255.0,12h
dhcp-option=3,10.20.30.1
dhcp-option=6,10.20.30.1
domain-needed
bogus-priv
log-dhcp
