# CCTV-audit Access Point (wlan2 / RT5370). WiFi-only IP-cam menyambung ke sini.
interface=wlan2
driver=nl80211
ssid=CCTV-AUDIT
country_code=ID
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=CctvAudit2026!
